services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db-data:/data/db
      - ./mongo/data:/home/data
    working_dir: /home/data

  backend:
    image: node:alpine
    ports:
      - 3000:3000
    working_dir: /home/app
    volumes:
      - ./backend:/home/app
    command: sh -c "npm install && npm run dev"

volumes:
  db-data: {}