services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db-data:/data/db
      - ./mongo/data:/home/data
    working_dir: /home/data

  backend:
    image: node
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://root:password@db:5432/app
      - JWT_SECRET=secret
      - MONGO_URL=mongodb://root:password@mongodb:27017/app?authSource=admin
    ports:
      - 3000:3000
    working_dir: /home/app
    volumes:
      - ./backend:/home/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
      - mongodb

  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  db-data: {}
  pg-data: {}